### PR TITLE
fix: handle interruption signals when on run

### LINKED ISSUE #412: [BUG] Terramate do not wait to its backgroung processes when a stop signal is sent
**Describe the bug**

Terraform is still running after Terramate has stopped completely due to a stop signal (control-c).

**To Reproduce**

1. Given a very [simple project](https://github.com/alvsanand/playing-with-terramate) with several stacks. 
2. Run command 'terramate run terraform apply' and send a stop signal with control-c while Terraform is aplying changes.
3. See error

**Expected behavior**

Terramate exit and all its processes.

**Log Output**

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Stopping operation...

~/workspace/playing-with-terramate$ ^C
~/workspace/playing-with-terramate$ ╷
│ Error: execution halted
│ 
│ 

**Environment (please complete the following information):**
 - OS: Ubuntu
 - OS Version: Ubuntu 20.04
 - Git Version: 2.25.1
 - Terramate Version: 0.1.7

**Additional context**

error_terrmate_exit_but_terraform_still_working

### PR DESCRIPTION
**Pull request by katcipis**
Currently Terramate will exit as soon as it gets an interruption signal, not waiting for the child process to exit. This PR introduces waiting for the child process to finish before exiting Terramate + It will force kill the child process after receiving 3 interruption signals.

Closes #412

### CODE REVIEW

File: cmd/terramate/cli/cli.go [hunk 1]
```diff
@@ -935,40 +934,28 @@ func (c *cli) runOnStacks() {
...
-		cmd.Env = os.Environ()
-		cmd.Stdin = c.stdin
-		cmd.Stdout = c.stdout
-		cmd.Stderr = c.stderr
-
-		logger := log.With().
-			Str("cmd", strings.Join(c.parsedArgs.Run.Command, " ")).
-			Stringer("stack", stack).
-			Logger()
+	err = run.Exec(
```
Comment (katcipis) [inline cmd/terramate/cli/cli.go:937]: Since run is more involved now with the signal handling I extracted it from the cli. It creates goroutines and changes signal handlers etc.

File: cmd/terramate/cli/cli.go [hunk 2]
```diff
@@ -935,40 +934,28 @@ func (c *cli) runOnStacks() {
...
-					Err(err).
-					Msg("failed to execute command")
-			} else {
-				logger.Fatal().
-					Err(err).
-					Msg("failed to execute command")
+		var errs *errors.List
+		if errors.As(err, &errs) {
+			for _, err := range errs.Errors() {
+				logger.Warn().Err(err).Send()
```
Comment (katcipis) [inline cmd/terramate/cli/cli.go:953]: here there is a slight change in behavior, before when there was no continue on error the message would be fatal. Now the message is always a warning and then we exit with an error status code. Since exiting with the err status code is the most important part it seems this change is OK, given that it simplifies the handling of the errors (doesn't matter if it is one or N errors).

File: run/exec.go [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+
+		logger := logger.With().
+			Stringer("stack", stack).
+			Logger()
+
+		logger.Info().Msg("Running")
+
+		// The child process should not get signals directly since
+		// we want to handle first interrupt differently.
+		cmd.SysProcAttr = &syscall.SysProcAttr{
```
Comment (katcipis) [inline run/exec.go:91]: Without this I can't implement the behavior of first interruption not being sent to the child process. But after that the child process will not receive any other signal than interruptions sent from terramate, at first glance this seems OK but I could be missing something and some other signal may need to be relayed to the child process immediately :thinking:

Comment (i4ki) [reply run/exec.go:91]: I think now the child process cannot read from the TTY anymore. 

Can you confirm that?
```
$ terramate run -- terraform console
```
here it hangs without reading/writing to the terminal.

Comment (katcipis) [reply run/exec.go:90]: Hmm yeah there is no more TTY x_x. Thanks for pointing out.

File: run/exec.go [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+		}
+
+		cmds <- cmd
+		interruptions := 0
+		cmdIsRunning := true
+
+		for cmdIsRunning {
+			select {
+			case sig := <-signals:
+				logger.Trace().
```
Comment (i4ki) [inline run/exec.go:97]: What do you think of logging them as `info` here? Because this is a kinda useful feedback, so users know that terramate is aware of the SIGINT sent.

Comment (katcipis) [reply run/exec.go:97]: hmm for the kill I added as Info but on this case it seemed that maybe we would generate too much noise...but I was on the fence. Will change to Info for now :+1:

**Review by i4ki — APPROVED** [review]
LGTM
