### PR TITLE
fix: checkGit() called for non-git repos

### LINKED ISSUE #402: [BUG] terramate run terraform init etc. crashes
**Describe the bug**
'terramate generate' works great, and creates the tf files in a stack. And these files work with direct terraform invocation (ie. terraform init, terraform plan etc.) But if I try 'terramate run terraform init' etc. I get a runtime error:

erramate run terraform plan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13a43db]

goroutine 1 [running]:
github.com/mineiros-io/terramate/git.(*Git).Remotes(0x0)
	github.com/mineiros-io/terramate/git/git.go:325 +0x21b
github.com/mineiros-io/terramate/cmd/terramate/cli.project.checkDefaultRemote({{0xc0000ae700, 0x44}, {0xc0000ae700, 0x6a}, 0x0, {{0xc0000ae700, 0x44}, 0xc0001e0df8, 0x0}, {0x0, ...}, ...})
	github.com/mineiros-io/terramate/cmd/terramate/cli/project.go:184 +0x292
github.com/mineiros-io/terramate/cmd/terramate/cli.(*cli).checkGit(0xc000292b60)
	github.com/mineiros-io/terramate/cmd/terramate/cli/cli.go:363 +0x2d9
github.com/mineiros-io/terramate/cmd/terramate/cli.(*cli).runOnStacks(0xc000292b60)
	github.com/mineiros-io/terramate/cmd/terramate/cli/cli.go:878 +0x2f0
github.com/mineiros-io/terramate/cmd/terramate/cli.(*cli).run(0xc000292b60)
	github.com/mineiros-io/terramate/cmd/terramate/cli/cli.go:336 +0x514
github.com/mineiros-io/terramate/cmd/terramate/cli.Exec({0xc0000b0010, 0x3, 0x3}, {0x15abee0, 0xc0000a2000}, {0x15abf00, 0xc0000a2008}, {0x15abf00, 0xc0000a2010})
	github.com/mineiros-io/terramate/cmd/terramate/cli/cli.go:139 +0xb7
main.main()
	github.com/mineiros-io/terramate/cmd/terramate/main.go:24 +0x7a
**To Reproduce**

I am calling a module via a source of a relative path that leads to a directory outside of the terramate root, so maybe that is a
factor

Just running 'terramate run terraform <cmd>' with terraform version 1.1.7 (or 1.2.2) and terramate 0.1.5

**Expected behavior**
Expect the terraform command to be executed

**Log Output**
Add logs from Terramate to help debug your problem.

**Environment (please complete the following information):**
 - OS: OSX
 - OS Version Big Sur 11.6.5
 - Git Version N/A
 -  - Terramate Version 0.1.5

**Additional context**

### PR DESCRIPTION
**Pull request by i4ki**
# Reason for This Change

The checks for git were running for non-git environments.

## Description of Changes

A guard was added to checkGit() and the tests were reused for git/nongit envs so we catch those related issues.

Closes #402

### CODE REVIEW

File: cmd/terramate/e2etests/run_test.go [hunk 1]
```diff
@@ -632,18 +639,27 @@ func TestRunWants(t *testing.T) {
...
 
-			cli := newCLI(t, filepath.Join(s.RootDir(), tc.wd))
-			assertRunResult(t, cli.stacksRunOrder(), tc.want)
+				cli := newCLI(t, filepath.Join(s.RootDir(), tc.wd))
+				assertRunResult(t, cli.stacksRunOrder(), tc.want)
 
-			// required because `terramate run` requires a clean repo.
-			git := s.Git()
-			git.CommitAll("everything")
+				if s.IsGit() {
```
Comment (katcipis) [inline cmd/terramate/e2etests/run_test.go:654]: hmm maybe HasGit ? like "sandbox has git ?"

**Review by katcipis — APPROVED** [review]
LGTM + ignorable comments
